/**
 * Contour-line "wave surface" — echoes the wireframe waves in the Ahadubit
 * company profile. The artwork lives in static, cacheable SVG files under
 * /public/waves (generated by scripts/generate-waves.mjs) so it stays out of
 * the HTML and the React payload.
 */
export type WaveVariant = "hero" | "page" | "cta" | "work";

export default function Waves({
  variant,
  className = "",
  eager = false,
}: {
  variant: WaveVariant;
  className?: string;
  eager?: boolean;
}) {
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={`/waves/${variant}.svg`}
      alt=""
      aria-hidden="true"
      width={1200}
      height={700}
      decoding="async"
      loading={eager ? "eager" : "lazy"}
      className={`waves ${className}`}
    />
  );
}
